spring.application.name=sunrise-dental-backend
spring.datasource.url=jdbc:mysql://localhost:3306/dental_clinic_db?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret Key (Base64 Encoded Key - 256 bits minimum)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

app.backup.directory=backups
